version: 2
builds:
  - skip: true
    main: ./main.go
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Version }}-next"
release:
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore'