language: go
go:
  - 1.14.x
os:
  - linux
services:
  - docker

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.27.0
  - go get -u golang.org/x/lint/golint
script:
  - go test ./... -coverprofile=coverage.out
  - go tool cover -func=coverage.out
  - golangci-lint run ./...
  - golint ./...
  - go build ./...