language: go
go:
  - 1.14.x
os:
  - linux
services:
  - docker

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.27.0
script:
  - golangci-lint run ./...
  - go build ./...