name: Build images

on:
  push:
    branches: master
  release:
    types:
      - published

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push ${{github.event.release.tag_name }}
        id: docker_build_release
        uses: docker/build-push-action@v4
        if: ${{ github.event.release.tag_name != '' }}
        with:
          push: true
          tags: ghcr.io/bakito/dns-checker:latest,ghcr.io/bakito/dns-checker:${{ github.event.release.tag_name }}
          platforms: linux/amd64
          provenance: false
          build-args: VERSION=${{ github.event.release.tag_name }}

      - name: Build and push master
        id: docker_build_master
        uses: docker/build-push-action@v4
        if: ${{ github.event.release.tag_name == '' }}
        with:
          push: true
          tags: ghcr.io/bakito/dns-checker:master
          platforms: linux/amd64
          provenance: false
          build-args: VERSION=master
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
